/**
 * Formatters for AI review comments and responses
 * @module formatters/commentFormatter
 */

const { getRuleLink } = require("../utils/docLinks");

/**
 * Extracts text from AI API response
 * Handles multiple response formats:
 * 1. Google Gemini format (candidates array)
 * 2. Direct output_text field (OpenAI Responses API)
 * 3. Nested output array with message content (OpenAI Responses API)
 * 4. Chat Completions format (OpenAI fallback)
 *
 * @param {object} data - The API response data
 * @returns {string} Extracted text or empty string
 */
function extractResponseText(data) {
  // Format 1: Google Gemini API format
  if (Array.isArray(data?.candidates) && data.candidates.length > 0) {
    const candidate = data.candidates[0];
    if (candidate?.content?.parts && Array.isArray(candidate.content.parts)) {
      const textParts = candidate.content.parts
        .filter(part => typeof part?.text === "string")
        .map(part => part.text);
      if (textParts.length > 0) {
        return textParts.join("\n");
      }
    }
  }

  // Format 2: Direct output_text field (OpenAI Responses API)
  if (typeof data?.output_text === "string" && data.output_text.trim()) {
    return data.output_text;
  }

  // Format 3: Responses API with output array (OpenAI)
  if (Array.isArray(data?.output)) {
    const chunks = [];
    for (const part of data.output) {
      if (part?.type === "message" && Array.isArray(part.content)) {
        for (const contentItem of part.content) {
          if (contentItem?.type === "output_text" && typeof contentItem.text === "string") {
            chunks.push(contentItem.text);
          }
        }
      }
    }
    if (chunks.length > 0) {
      return chunks.join("\n");
    }
  }

  // Format 4: Chat Completions API fallback (OpenAI)
  const choice = data?.choices?.[0];
  if (choice?.message?.content && typeof choice.message.content === "string") {
    return choice.message.content;
  }

  return "";
}

/**
 * Formats a single issue for inline comment
 * @param {object} issue - The issue object
 * @param {string} issue.id - Issue ID (e.g., "CQ-4.08")
 * @param {string} issue.path - File path
 * @param {number} issue.line - Line number
 * @param {string} issue.message - Issue message
 * @param {string} issue.suggestion - Suggestion for fix
 * @returns {string} Formatted comment body
 */
function formatIssueComment(issue) {
  const ruleLink = getRuleLink(issue.id);

  const lines = [
    `### 🔍 ${ruleLink}`,
    "",
    issue.message || "",
    "",
  ];

  if (issue.suggestion) {
    lines.push(`**💡 Suggestion:** ${issue.suggestion}`);
    lines.push("");
  }

  lines.push("---");
  lines.push(`_🤖 CodeGuardian AI • [📖 View all rules](https://clca-dev.atlassian.net/wiki/spaces/NL/pages/312246283/Frontend+Code+Quality+Architecture+Standards)_`);

  return lines.filter(line => line !== "").join("\n");
}

/**
 * Formats the AI result as a markdown comment
 * @param {object} result - The parsed AI result
 * @param {string} model - The model used
 * @param {number} rawDiffLength - The raw diff length in characters
 * @returns {string} Formatted markdown comment
 */
function formatMarkdownComment(result, model, rawDiffLength) {
  const lines = [
    "# 🔍 CodeGuardian AI Review",
    "",
    `> 🧠 **Powered by:** \`${model}\` | 📊 **Analyzed:** ${rawDiffLength} chars`,
    "",
    "---",
    "",
  ];

  if (result?.issues && Array.isArray(result.issues) && result.issues.length > 0) {
    lines.push(`## ⚠️ Found ${result.issues.length} Issue${result.issues.length > 1 ? 's' : ''}`);
    lines.push("");
    result.issues.forEach((issue, index) => {
      const emoji = index === 0 ? "🔴" : index === 1 ? "🟠" : "🟡";
      const ruleLink = getRuleLink(issue.id);
      lines.push(`### ${emoji} ${index + 1}. ${ruleLink}`);
      lines.push(`**Location:** \`${issue.path}:${issue.line}\``);
      lines.push("");
      if (issue.message) {
        lines.push(`**Issue:** ${issue.message}`);
        lines.push("");
      }
      if (issue.suggestion) {
        lines.push(`💡 **Suggestion:** ${issue.suggestion}`);
        lines.push("");
      }
    });
  } else {
    lines.push("## ✅ All Clear!");
    lines.push("");
    lines.push("No code quality issues detected. Great work! 🎉");
    lines.push("");
  }

  lines.push("---");
  lines.push("");
  lines.push("<details>");
  lines.push("<summary>📋 View Full Analysis</summary>");
  lines.push("");
  lines.push("```json");
  lines.push(JSON.stringify(result, null, 2));
  lines.push("```");
  lines.push("</details>");
  lines.push("");
  lines.push("---");
  lines.push("_🤖 Generated by **CodeGuardian AI** - Your automated code quality companion_");
  lines.push("");
  lines.push("📖 **[View Code Quality Rules Documentation](https://clca-dev.atlassian.net/wiki/spaces/NL/pages/312246283/Frontend+Code+Quality+Architecture+Standards)**");

  return lines.join("\n");
}

/**
 * Validates that an issue has required fields for posting
 * @param {object} issue - The issue to validate
 * @returns {boolean} True if valid
 */
function isValidIssue(issue) {
  return (
    issue &&
    typeof issue.path === "string" &&
    issue.path.length > 0 &&
    Number.isInteger(issue.line) &&
    issue.line > 0
  );
}

module.exports = {
  extractResponseText,
  formatIssueComment,
  formatMarkdownComment,
  isValidIssue,
};
